export const selectors = {
  addSection: '.add-section',
  addSkill: '.add-skill',
  backToOriginal: '.back-to-original',
  customizeResume: '.customize-resume',
  downloadPdf: '.download-pdf',
  editOnly: '.edit-only',
  editToolbar: '.edit-toolbar',
  finishEditing: '.finish-editing',
  layoutSelect: '.layout-select',
  photoInput: '.photo-input',
  profileImage: '.profile-image',
  resetResume: '.reset-resume',
  resume: '.resume',
  saveStatus: '.save-status',
  startBlank: '.start-blank',
  startDialog: '.start-dialog',
  startExample: '.start-example',
} as const;
